name:                january-tests-haskell
version:             0.1.0.0
github:              "plumenator/january-tests-haskell"
license:             BSD3
author:              "Karthik Ravikanti"
maintainer:          "karthik.ravikanti@gmail.com"
copyright:           "2020 Karthik Ravikanti"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/plumenator/january-tests-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  january-tests-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - january-tests-haskell

tests:
  january-tests-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - january-tests-haskell
    - hspec
